const content = [
  {
    Language: "EN",
    Title: ["Programming", "Martial Arts", "Learning", "Farming"],
    body: [
      "My programming journey represents a long-pursued dream of mine to establish a career in the field of IT. I seized the opportunity to enhance my skills through bootcamps, as well as courses on Udemy and Coursera. When faced with a busy day and unable to dedicate extended periods to my projects, I make an effort to engage in challenges and courses on SoloLearn. As a result of these experiences, I have acquired a solid understanding of programming languages such as Java, HTML, JavaScript, CSS, TypeScript, and Linux Bash. Additionally, I have taken initial steps in learning languages like Python, C, Haskell, and Pascal.",
      "Martial arts is my way of releasing stress, keeping my body and mind fit for every situation, and reflecting on how to become better. Since I was a child, I have practiced various disciplines from karate to boxing, which has given me great logical and spatial thinking abilities. I have learned to abstract the positions of objects or myself in a specific environment, work effectively in teams, and share my knowledge with peers who are also learning alongside me.",
      "Learning is also one of my pursuits. I embrace the mindset that a day without acquiring new knowledge is a wasted day. Some of the great minds, like Leonardo da Vinci and Darwin, weren't born geniuses but worked tirelessly through passion and determination. I strive to follow their example. I have completed a bachelor's in education, acquiring the skills to learn new subjects and share my knowledge with groups of people. In any team I am part of, I endeavor to achieve and share the required knowledge, fostering understanding and paving the way for excellence.",
      "Farming is one of my hidden passions. I don't share it too often, but I enjoy watching videos on aquaponics, self-sufficiency, and how to tend to your garden. It's one of those works that isn't mentioned too much but is equally important and necessary for everyone. I immerse myself in it when I have a garden at home, or when I'm playing video games like Farm Manager or Farm Simulator. I take a few minutes to watch the fields being plowed and the crops grow.",
    ],
  },
  {
    Language: "ES",
    Title: ["Programación", "Artes Marciales", "Aprendizaje", "Agricultura"],
    body: [
      "Mi camino en la programación representa un sueño que he perseguido durante mucho tiempo de establecer una carrera en el campo de la tecnología de la información. Aproveché la oportunidad para mejorar mis habilidades a través de bootcamps, así como cursos en Udemy y Coursera. Cuando me enfrento a un día ocupado y no puedo dedicar períodos extendidos a mis proyectos, me esfuerzo por participar en desafíos y cursos en SoloLearn. Como resultado de estas experiencias, he adquirido una comprensión sólida de lenguajes de programación como Java, HTML, JavaScript, CSS, TypeScript y Linux Bash. Además, he dado los primeros pasos en el aprendizaje de idiomas como Python, C, Haskell y Pascal.",
      "Las artes marciales son mi forma de liberar el estrés, mantener mi cuerpo y mente en forma para cualquier situación y reflexionar sobre cómo mejorar. Desde que era niño, he practicado varias disciplinas, desde karate hasta boxeo, lo que me ha dado grandes habilidades de pensamiento lógico y espacial. He aprendido a abstraer las posiciones de objetos o de mí mismo en un entorno específico, trabajar eficientemente en equipos y compartir mi conocimiento con compañeros que también están aprendiendo junto a mí.",
      "El aprendizaje también es una de mis búsquedas. Acepto la mentalidad de que un día sin adquirir nuevos conocimientos es un día perdido. Algunas de las mentes brillantes, como Leonardo da Vinci y Darwin, no nacieron genios, sino que trabajaron incansablemente con  pasión y determinación. Me esfuerzo por seguir su ejemplo. He completado una licenciatura en educación, adquiriendo las habilidades para aprender nuevas materias y compartir mi conocimiento con grupos de personas. En cualquier equipo del que forme parte, me esfuerzo por alcanzar y compartir el conocimiento necesario, fomentando la comprensión y abriendo el camino hacia la excelencia.",
      "La agricultura es una de mis pasiones ocultas. No la comparto demasiado a menudo, pero disfruto viendo videos sobre acuaponía, autosuficiencia y cómo cuidar tu jardín. Es uno de esos trabajos que no se menciona demasiado pero es igualmente importante y necesario para todos. Me sumerjo en ello cuando tengo un jardín en casa, o cuando juego videojuegos como Farm Manager o Farm Simulator. Dedico unos minutos a ver los campos siendo arados y los cultivos creciendo.",
    ],
  },
  {
    Language: "DE",
    Title: ["Programmierung", "Kampfkunst", "Lernen", "Landwirtschaft"],
    body: [
      "Meine Programmierreise repräsentiert einen lang ersehnten Traum von mir, eine Karriere im IT-Bereich zu etablieren. Ich habe die Gelegenheit ergriffen, meine Fähigkeiten durch Bootcamps sowie Kurse auf Udemy und Coursera zu verbessern. Wenn ich mit einem vollen Tag konfrontiert bin und keine langen Zeiträume meinen Projekten widmen kann, bemühe ich mich, an Herausforderungen und Kursen auf SoloLearn teilzunehmen. Als Ergebnis dieser Erfahrungen habe ich ein solides Verständnis von Programmiersprachen wie Java, HTML, JavaScript, CSS, TypeScript und Linux Bash erlangt. Zusätzlich habe ich erste Schritte unternommen, um Sprachen wie Python, C, Haskell und Pascal zu lernen.",
      "Kampfkunst ist meine Art, Stress abzubauen, meinen Körper und Geist für jede Situation fit zu halten und darüber nachzudenken, wie ich besser werden kann. Seit meiner Kindheit praktiziere ich verschiedene Disziplinen von Karate bis Boxen, was mir großartige logische und räumliche Denkfähigkeiten verliehen hat. Ich habe gelernt, die Positionen von Objekten oder mir selbst in einer bestimmten Umgebung abstrakt zu erfassen, effektiv in Teams zu arbeiten und mein Wissen mit Gleichgesinnten zu teilen, die ebenfalls neben mir lernen.",
      "Lernen ist ebenfalls eine meiner Verfolgungen. Ich bejahe die Einstellung, dass ein Tag ohne das Erlangen neuer Kenntnisse ein verschwendeter Tag ist. Einige der großen Köpfe wie Leonardo da Vinci und Darwin wurden nicht als Genies geboren, sondern arbeiteten durch Leidenschaft und Entschlossenheit unermüdlich. Ich strebe danach, ihrem Beispiel zu folgen. Ich habe einen Bachelor in Lehramt  abgeschlossen und dabei die Fähigkeiten erworben, neue Fächer zu lernen und mein Wissen mit Gruppen von Menschen zu teilen. In jedem Team, dem ich angehöre, strebe ich danach, das erforderliche Wissen zu erlangen und zu teilen, um das Verständnis zu fördern und den Weg zur Exzellenz zu ebnen.",
      "Landwirtschaft ist eine meiner verborgenen Leidenschaften. Ich teile sie nicht allzu oft, aber ich schaue gerne Videos über Aquaponik, Selbstversorgung und wie man sich um seinen Garten kümmert. Es ist eine dieser Arbeiten, die nicht zu oft erwähnt wird, aber für jeden genauso wichtig und notwendig ist. Ich tauche darin ein, wenn ich einen Garten zu Hause habe, oder wenn ich Videospiele wie Farm Manager oder Farm Simulator spiele. Ich nehme mir ein paar Minuten Zeit, um zuzusehen, wie die Felder gepflügt und die Pflanzen wachsen.",
    ],
  },
];

export default content;

